notifications:
  email: false
language: python
services:
    - postgresql

## This is necessary because of https://github.com/travis-ci/travis-ci/issues/6972
addons:
    postgresql: 9.6
    apt:
        packages:
            postgresql-9.6-postgis-2.3
##

env:
  global:
    POSTGIS_DB="postgresql://postgres@localhost/slingshot_test"
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36-integration
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=safety
    - python: 3.6
      env: TOX_ENV=coveralls
before_script:
    - psql -U postgres -c "CREATE DATABASE slingshot_test;"
    - psql -U postgres -d slingshot_test -c "CREATE EXTENSION postgis;"
    - psql -U postgres -d slingshot_test -c "CREATE SCHEMA geodata;"
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
