notifications:
  email: false
language: python
matrix:
  include:
    - env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.5
      env: TOX_ENV=setup
    - python: 3.5
      env: TOX_ENV=coveralls
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
