language: python
services:
    - postgresql
dist: xenial
python: 3.7

## This is necessary because of https://github.com/travis-ci/travis-ci/issues/6972
addons:
    postgresql: 9.6
    apt:
        packages:
            postgresql-9.6-postgis-2.4

##
# moto has a problem with credentials (https://github.com/spulec/moto/issues/1924)
# and the solution is to just set the AWS creds to anything. They will have
# to be set individually for each environment in the job matrix that runs
# tests (i.e. py37 and coveralls) rather than globally because they would
# overwrite the real AWS creds set through the Travis UI. Those will be
# needed for deployment.
##
env:
  global:
    - PG_DATABASE="postgresql://postgres@localhost/slingshot_test"
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=safety
    - TOX_ENV=py37 AWS_SECRET_ACCESS_KEY=secret AWS_ACCESS_KEY_ID=key
##
# Coveralls appears to be broken. The test coverage is passing but it fails
# when trying to submit the coverage.
##
#    - TOX_ENV=coveralls AWS_SECRET_ACCESS_KEY=secret AWS_ACCESS_KEY_ID=key
before_script:
    - psql -U postgres -c "CREATE DATABASE slingshot_test;"
    - psql -U postgres -d slingshot_test -c "CREATE EXTENSION postgis;"
    - psql -U postgres -d slingshot_test -c "CREATE SCHEMA geodata;"
before_install:
  ## This is necessary because of https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
jobs:
  include:
    - stage: Deploy
      before_install: skip
      install: pip install pipenv awscli
      before_script: skip
      script: skip
      before_deploy: make dist
      deploy:
        skip_cleanup: true
        provider: script
        script: make publish
